-- ═══════════════════════════════════════════════════════════════════════════
-- price_history-Swap v2 — KOMPLETT, in einem Lauf  (20.08.2026)
-- ERSETZT ..._price_history_swap.sql UND ..._swap_FIX.sql (beide nicht mehr
-- verwenden!). Ebenso ersetzt: Diaet-v2-Reste (Index-Drops, Rollup, pg_cron —
-- die wurden mit dem gescheiterten DELETE zurueckgerollt und sind hier
-- erneut enthalten).
--
-- ERKENNTNIS aus zwei Fehlversuchen (BUG-018): Der SQL-Editor schickt einen
-- Lauf als EINE implizite Transaktion — scheitert EIN Statement, wird ALLES
-- zurueckgerollt (deshalb verschwand price_history_neu nach dem 2BP01-Fehler
-- wieder). Fuer diesen Swap ist das ideal: er ist damit atomar. Der 2BP01 kam
-- daher, dass die Alt-Tabelle ein Vor-Repo-SERIAL hat — "including defaults"
-- kopierte den nextval auf die ALTE Sequenz mit; der Default wird jetzt VOR
-- dem Drop abgeloest.
-- Die -52 MB von heute Mittag stammten uebrigens vom manuell gelaufenen
-- VACUUM FULL (Index-Defragmentierung), nicht von der Diaet.
--
-- ZEITFENSTER: 05-15 UTC (nur der Preis-Updater schreibt price_history).
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1) Frische Tabelle, Behalter kopieren ──────────────────────────────────
create table public.price_history_neu
  (like public.price_history including defaults including identity including constraints);

insert into public.price_history_neu
select ph.* from public.price_history ph
where ph.id in (
  select id from (
    select id, price,
           lag(price) over (partition by player_slug, scarcity, eligibility
                            order by recorded_at) as prev
    from public.price_history
  ) t
  where prev is null or price is distinct from prev
);

-- ── 2) Geliehenen Zaehler abloesen, tauschen, eigenes Identity ─────────────
alter table public.price_history_neu alter column id drop default;
drop table public.price_history;      -- nimmt alte Sequenz + tote Indizes mit
alter table public.price_history_neu rename to price_history;
alter table public.price_history
  alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('public.price_history', 'id'),
              (select coalesce(max(id), 1) from public.price_history));

-- ── 3) Nur die zwei lebendigen Indizes (Report 20.08.) ─────────────────────
alter table public.price_history
  add constraint price_history_slug_scarcity_date_elig_key
  unique (player_slug, scarcity, recorded_at, eligibility);   -- Upsert-Ziel
create index price_history_recorded_at_idx on public.price_history (recorded_at);
-- bewusst KEIN Primaerschluessel (0 Benutzungen, 37 MB) und KEIN
-- player_slug_scarcity_idx (Praefix des Unique-Keys)

-- ── 4) Lockdown exakt reapplizieren (BUG-012!) ─────────────────────────────
alter table public.price_history enable row level security;
alter table public.price_history force  row level security;
revoke all on public.price_history from anon, authenticated;

-- ── 5) Aus der zurueckgerollten Diaet erneut: card_prices-Praefix-Index ────
drop index if exists public.card_prices_player_slug_idx;

-- ── 6) Wochen-Rollup + Wochenjob (ebenfalls zurueckgerollt gewesen) ────────
create or replace function public.price_history_rollup(p_keep_days int default 90)
returns int
language plpgsql security definer set search_path = public as $$
declare n int;
begin
  -- Aelter als p_keep_days: je Karte und Kalenderwoche nur den JUENGSTEN
  -- Punkt behalten. Der letzte Stand einer Karte bleibt immer (rn = 1).
  delete from public.price_history ph
  using (
    select id,
           row_number() over (
             partition by player_slug, scarcity, eligibility,
                          date_trunc('week', recorded_at::timestamp)
             order by recorded_at desc, id desc) as rn
    from public.price_history
    where recorded_at < current_date - p_keep_days
  ) t
  where ph.id = t.id and t.rn > 1;
  get diagnostics n = row_count;
  return n;
end $$;
revoke all on function public.price_history_rollup(int) from public;

do $$
begin
  create extension if not exists pg_cron;
  perform cron.schedule('price_history_rollup_weekly', '30 6 * * 1',
                        'select public.price_history_rollup(90)');
exception when others then
  raise notice 'pg_cron nicht verfuegbar (%): bitte melden, dann haengen wir den Job an den Harvester', sqlerrm;
end $$;

-- ── Kontrolle (letzte Ausgabe des Laufs) ───────────────────────────────────
select count(*)                                                        as zeilen,
       pg_size_pretty(pg_total_relation_size('public.price_history'))  as price_history_gesamt,
       (select count(*) from (
          select price, lag(price) over (partition by player_slug, scarcity, eligibility
                                         order by recorded_at) as prev
          from public.price_history) t
        where prev is not null and price = prev)                       as verbliebene_duplikate,
       (select count(*) from pg_indexes
        where schemaname = 'public' and tablename = 'price_history')   as indizes_anzahl;
-- Erwartung: ~520k Zeilen · unter 100 MB · 0 Duplikate · 2 Indizes
