-- ═══════════════════════════════════════════════════════════════════════════
-- Swap-Reparatur (20.08.2026) — fuehrt den in ..._price_history_swap.sql
-- begonnenen Tausch zu Ende.
--
-- WAS PASSIERT WAR: Die alte Tabelle stammt aus der Vor-Repo-Zeit, ihre id ist
-- ein altes SERIAL (Default nextval auf price_history_id_seq), KEIN Identity.
-- "like ... including defaults" kopierte diesen Default mit — die neue Tabelle
-- hing damit am Zaehler der alten, und Postgres verweigerte den Drop (2BP01).
-- KEIN CASCADE verwenden: das wuerde der neuen Tabelle den Default unterm
-- Hintern wegziehen.
--
-- price_history_neu existiert bereits und enthaelt die Behalter-Zeilen.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1) Nachzuegler: alles, was der Updater SEIT dem Kopieren geschrieben hat
--       (ids kommen aus der gemeinsamen Sequenz, sind also strikt groesser)
insert into public.price_history_neu
select * from public.price_history ph
where ph.id > (select coalesce(max(id), 0) from public.price_history_neu);

-- ── 2) Eigenen Zaehler geben, dann tauschen ────────────────────────────────
alter table public.price_history_neu alter column id drop default;
drop table public.price_history;              -- nimmt die alte Sequenz mit (owned)
alter table public.price_history_neu rename to price_history;
alter table public.price_history
  alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('public.price_history', 'id'),
              (select coalesce(max(id), 1) from public.price_history));

-- ── 3) Indizes neu (wie im Swap geplant) ───────────────────────────────────
alter table public.price_history
  add constraint price_history_slug_scarcity_date_elig_key
  unique (player_slug, scarcity, recorded_at, eligibility);
create index price_history_recorded_at_idx on public.price_history (recorded_at);
-- bewusst kein Primaerschluessel (0 Benutzungen, 37 MB tot — Report 20.08.)

-- ── 4) Lockdown exakt reapplizieren (BUG-012!) ─────────────────────────────
alter table public.price_history enable row level security;
alter table public.price_history force  row level security;
revoke all on public.price_history from anon, authenticated;

-- ── Kontrolle ──────────────────────────────────────────────────────────────
select count(*)                                                        as zeilen,
       pg_size_pretty(pg_total_relation_size('public.price_history'))  as gesamt_neu,
       (select count(*) from (
          select price, lag(price) over (partition by player_slug, scarcity, eligibility
                                         order by recorded_at) as prev
          from public.price_history) t
        where prev is not null and price = prev)                       as verbliebene_duplikate;
